export const theme = {
  colors: {
    background: '#fff4d6',
    backgroundAlt: '#ffe5b3',
    surface: '#ffefcf',
    accent: '#f28c1f',
    accentSoft: '#f7b955',
    textPrimary: '#542c0b',
    textSecondary: '#7a4a1d',
    textMuted: '#b07033',
    danger: '#f56565',
    success: '#36c07d',
    shadowDark: '#d27a32',
    shadowLight: '#fff8e6',
  },
};

export const neumorphicStyles = {
  surface: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    shadowColor: theme.colors.shadowDark,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
  },
  concave: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.shadowDark,
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  pressable: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    shadowColor: theme.colors.shadowDark,
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
};
